# Generated by Django 4.0.4 on 2022-06-10 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=222)),
                ('name', models.CharField(max_length=222)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=333)),
                ('user3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.people')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=333)),
                ('user2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.people')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=222)),
                ('city', models.CharField(max_length=222)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.people')),
            ],
        ),
    ]
