# Generated by Django 4.0.4 on 2022-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=7)),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doc',
            new_name='doctor_name',
        ),
    ]
