# Generated by Django 4.0.4 on 2022-06-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_rename_doc_doctor_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quatity',
            field=models.IntegerField(default=2, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1, max_length=7),
        ),
    ]
